swiftmailer:
    # url: '%env(MAILER_URL)%'
    # spool: { type: 'memory' }
    transport: gmail
    auth_mode: login
    port: 465
    host: smtp.gmail.com
    username: 'citrovsandbox'
    password: 'Ricore06.'
    spool: { type: 'memory' }
