swiftmailer:
    # url: '%env(MAILER_URL)%'
    transport: gmail
    auth_mode: login
    port: 465
    host: smtp.gmail.com
    username: 'citrovsandbox'
    password: 'Ricore06.'
    spool: { type: 'memory' }
    # transport: smtp
    # auth_mode: login
    # port: 465
    # host: in-v3.mailjet.com
    # username: '34a75ff3ce8f2d994d1966b3a7ebdd07'
    # password: '88e5484f76a16680b8959b8647afeca6'
    # spool: { type: 'memory' }
